version: '3.5'

services:
  tutorial:
    image: zzzcat/dispshell:latest
    tty: true
    working_dir: /work
    entrypoint: ./entrypoint.sh
    command: /bin/bash
    volumes:
        - .:/work
    environment:
      ANSIBLE_CONFIG: .
      ANSIBLE_USERNAME: ${ANSIBLE_USERNAME}
      ANSIBLE_PASSWORD: ${ANSIBLE_PASSWORD}
      USERNAME: ${USERNAME}
      SSHD_PORT: ${SSHD_PORT}
    secrets:
      - secret_key
      - public_key

secrets:
  secret_key:
    file: ./.ssh/ubuntu.key
  public_key:
    file: ./.ssh/ubuntu.key.pub