---
- hosts: ubuntu

  vars:
    - user_name: "{{ lookup('env', 'USERNAME') }}"
  gather_facts: no
  become: true

  tasks:
    - name: Install docker
      apt:
        update_cache: yes
        name:
          - docker.io

    - name: Install docker-compose
      apt:
        update_cache: yes
        name:
          - docker-compose

    - name: Add user to docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
